// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: proto/consensus/consensus.proto

package consensus

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Phase 1: Prepare-Promise phase
type PrepareRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ballot uint64 `protobuf:"varint,1,opt,name=Ballot,proto3" json:"Ballot,omitempty"`
}

func (x *PrepareRequest) Reset() {
	*x = PrepareRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_consensus_consensus_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrepareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareRequest) ProtoMessage() {}

func (x *PrepareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consensus_consensus_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareRequest.ProtoReflect.Descriptor instead.
func (*PrepareRequest) Descriptor() ([]byte, []int) {
	return file_proto_consensus_consensus_proto_rawDescGZIP(), []int{0}
}

func (x *PrepareRequest) GetBallot() uint64 {
	if x != nil {
		return x.Ballot
	}
	return 0
}

type PromiseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Promised bool `protobuf:"varint,1,opt,name=Promised,proto3" json:"Promised,omitempty"`
	// Ballot of previously accepted propose
	Ballot uint64 `protobuf:"varint,2,opt,name=Ballot,proto3" json:"Ballot,omitempty"`
	// Color accepted, according to previously accepted
	Color string `protobuf:"bytes,3,opt,name=Color,proto3" json:"Color,omitempty"`
}

func (x *PromiseResponse) Reset() {
	*x = PromiseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_consensus_consensus_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PromiseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromiseResponse) ProtoMessage() {}

func (x *PromiseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consensus_consensus_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromiseResponse.ProtoReflect.Descriptor instead.
func (*PromiseResponse) Descriptor() ([]byte, []int) {
	return file_proto_consensus_consensus_proto_rawDescGZIP(), []int{1}
}

func (x *PromiseResponse) GetPromised() bool {
	if x != nil {
		return x.Promised
	}
	return false
}

func (x *PromiseResponse) GetBallot() uint64 {
	if x != nil {
		return x.Ballot
	}
	return 0
}

func (x *PromiseResponse) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

// Phase 2: Propose-Accept phase
type ProposeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ballot uint64 `protobuf:"varint,1,opt,name=Ballot,proto3" json:"Ballot,omitempty"`
	Color  string `protobuf:"bytes,2,opt,name=Color,proto3" json:"Color,omitempty"`
}

func (x *ProposeRequest) Reset() {
	*x = ProposeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_consensus_consensus_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProposeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeRequest) ProtoMessage() {}

func (x *ProposeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consensus_consensus_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeRequest.ProtoReflect.Descriptor instead.
func (*ProposeRequest) Descriptor() ([]byte, []int) {
	return file_proto_consensus_consensus_proto_rawDescGZIP(), []int{2}
}

func (x *ProposeRequest) GetBallot() uint64 {
	if x != nil {
		return x.Ballot
	}
	return 0
}

func (x *ProposeRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type AcceptResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Accepted bool `protobuf:"varint,1,opt,name=Accepted,proto3" json:"Accepted,omitempty"`
}

func (x *AcceptResponse) Reset() {
	*x = AcceptResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_consensus_consensus_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptResponse) ProtoMessage() {}

func (x *AcceptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consensus_consensus_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptResponse.ProtoReflect.Descriptor instead.
func (*AcceptResponse) Descriptor() ([]byte, []int) {
	return file_proto_consensus_consensus_proto_rawDescGZIP(), []int{3}
}

func (x *AcceptResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_proto_consensus_consensus_proto protoreflect.FileDescriptor

var file_proto_consensus_consensus_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75,
	0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x28, 0x0a, 0x0e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x61, 0x6c, 0x6c, 0x6f, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x42, 0x61, 0x6c, 0x6c, 0x6f, 0x74, 0x22, 0x5b, 0x0a, 0x0f, 0x50,
	0x72, 0x6f, 0x6d, 0x69, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x50, 0x72, 0x6f, 0x6d, 0x69, 0x73, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x50, 0x72, 0x6f, 0x6d, 0x69, 0x73, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x61,
	0x6c, 0x6c, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x42, 0x61, 0x6c, 0x6c,
	0x6f, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x22, 0x3e, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x70,
	0x6f, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x61,
	0x6c, 0x6c, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x42, 0x61, 0x6c, 0x6c,
	0x6f, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x22, 0x2c, 0x0a, 0x0e, 0x41, 0x63, 0x63, 0x65,
	0x70, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x63,
	0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x41, 0x63,
	0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x32, 0x65, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x73, 0x65, 0x6e,
	0x73, 0x75, 0x73, 0x12, 0x2c, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x6d, 0x69, 0x73, 0x65, 0x12, 0x0f,
	0x2e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x10, 0x2e, 0x50, 0x72, 0x6f, 0x6d, 0x69, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2a, 0x0a, 0x06, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x12, 0x0f, 0x2e, 0x50, 0x72,
	0x6f, 0x70, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x41,
	0x63, 0x63, 0x65, 0x70, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x04, 0x5a,
	0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_consensus_consensus_proto_rawDescOnce sync.Once
	file_proto_consensus_consensus_proto_rawDescData = file_proto_consensus_consensus_proto_rawDesc
)

func file_proto_consensus_consensus_proto_rawDescGZIP() []byte {
	file_proto_consensus_consensus_proto_rawDescOnce.Do(func() {
		file_proto_consensus_consensus_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_consensus_consensus_proto_rawDescData)
	})
	return file_proto_consensus_consensus_proto_rawDescData
}

var file_proto_consensus_consensus_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_consensus_consensus_proto_goTypes = []interface{}{
	(*PrepareRequest)(nil),  // 0: PrepareRequest
	(*PromiseResponse)(nil), // 1: PromiseResponse
	(*ProposeRequest)(nil),  // 2: ProposeRequest
	(*AcceptResponse)(nil),  // 3: AcceptResponse
}
var file_proto_consensus_consensus_proto_depIdxs = []int32{
	0, // 0: Consensus.Promise:input_type -> PrepareRequest
	2, // 1: Consensus.Accept:input_type -> ProposeRequest
	1, // 2: Consensus.Promise:output_type -> PromiseResponse
	3, // 3: Consensus.Accept:output_type -> AcceptResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_consensus_consensus_proto_init() }
func file_proto_consensus_consensus_proto_init() {
	if File_proto_consensus_consensus_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_consensus_consensus_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrepareRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_consensus_consensus_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PromiseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_consensus_consensus_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProposeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_consensus_consensus_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_consensus_consensus_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_consensus_consensus_proto_goTypes,
		DependencyIndexes: file_proto_consensus_consensus_proto_depIdxs,
		MessageInfos:      file_proto_consensus_consensus_proto_msgTypes,
	}.Build()
	File_proto_consensus_consensus_proto = out.File
	file_proto_consensus_consensus_proto_rawDesc = nil
	file_proto_consensus_consensus_proto_goTypes = nil
	file_proto_consensus_consensus_proto_depIdxs = nil
}
