---
name: node2
increment: 2
timeout: 500ms
listen: 127.0.0.1:8002
peers:
  - name: node1
    address: 127.0.0.1:8001
  - name: node3
    address: 127.0.0.1:8003
  - name: node4
    address: 127.0.0.1:8004