---
name: node4
increment: 4
timeout: 500ms
listen: 127.0.0.1:8004
peers:
  - name:node1
    address: 127.0.0.1:8001
  - name:node2
    address: 127.0.0.1:8002
  - name:node3
    address: 127.0.0.1:8003